= Reto Reto CrowdStrike
include::_attributes.adoc[ puntos__**

Teniendo en cuenta la incidencia que sucedió el pasado 19 de julio con la actualización de Falcon Sensor de CrowdStrike, que contenía un fallo que obligaba a los computadores con el sistema operativo Windows de Microsoft a bloquearse, en este primer reto se implementará un automatismo para eliminar un fichero dañado en máquinas windows.

TIP: El detalle de las puntuaciones os puede servir como ayuda

== Detalle del reto

El reto consiste en la implementacion de un playbook que acceda a un servidor windows y elimine los ficheros que cumplan estos requisitos:

* Se encuentren dentro de la carpeta ``Crowdstrike`` en vuestro home de usuario
* Tienen extension ``.sys``
* Su fecha de creación es ``2024-07-22T13:17:00Z``

El playbook debe estar en Gitea y ser ejecutado desde Ansible Automation Platform.

El servidor windows ya esta configurado dentro del inventario ``Windows`` en AAP.

== Puntuacion

NOTE: No es necesario realizar todos los items, algunos de los items son opcionales y el reto se puede conseguir sin ellos

* Crear playbook en Gitea - **__10 puntos__**
* Sincronizar el proyecto en AAP para tener los ultimos cambios del repositorio del grupo de Gitea - **__15 puntos__**
* Crear job template en AAP:
** Utiizar credenciales proporcionados en AAP - **__5 puntos__**
** Utilizar inventario ``Windows`` proporcionado en AAP - **__5 puntos__**
* Mostrar en la ejecucion del playbook (debug):
** Los ficheros ``.sys`` del directorio ``Crowdstrike`` - **__5 puntos__**
** Los ficheros ``.sys`` del directorio ``Crowdstrike`` junto con su fecha de creación - **__10 puntos__**
* Utilizar un diccionario para la ejecucion del reto - **__20 puntos__**
* Borrar el fichero - **__20 puntos__**
* Utilizar la colección ansible.windows - **__10 puntos__**
