= Reto Tipos de Cambio
include::_attributes.adoc[ puntos__**

En este reto, mediante el uso de diferentes APIs y módulos de Ansible, se tendrá que crear un automatismo de ejecución periódica que compruebe el valor de diferentes tipos de cambio del BCE y actualice/fije los valores de la web de Banco de España teniendo en cuenta uno.

TIP: El detalle de las puntuaciones os puede servir como ayuda

== Detalle del reto

El reto consiste en la implementacion de un playbook que realice el siguiente flujo:

. Recupere el listado de monedas del Banco de España (incluye los valores actuales y los límites)
. Para cada moneda, recupere la información del Banco Central Europeo (incluye el valor actual)
. Dependiendo de los valores recibidos actualizar el valor de las moneda en Banco de España por:
.. Si el valor recuperado del BCE es mayor que el limite establecido por el BdE -> límite establecido
.. Si el valor recuperado del BCE es menor o igual que el limite establecido por el BdE -> valor del BCE

La web de Banco de España donde se muestran los tipos de cabio se puede visitar en ``\http://frontend-%USER%.apps.%SERVER%``

La información de la API de Banco de España es:

* URL: ``\http://backend-%USER%.apps.%SERVER%``
* Endpoints: 
** [GET] ``/app_rates``
** [POST] ``/app_rates`` with json body: ``{"currency": "<currency>","value": value}``

La información de la API del Banco Central Europeo es:

* URL: ``\http://backend-%USER%.apps.%SERVER%``
* Endpoints: 
** [GET] ``/bce_rates/<currency>``

El playbook debe estar en Gitea y ser ejecutado desde Ansible Automation Platform. En Ansible Automation Hub se ha incluido una colección que realiza la comunicación con BdE, BCE e implementa la lógica descrita anteriormente, **se puede utilizar pero la puntuación será mayor si se realiza el reto sin usar dicha colección**.

== Puntuación

NOTE: No es necesario realizar todos los items, algunos de los items son opcionales y el reto se puede conseguir sin ellos

* Crear playbook en Gitea - **__10 puntos__**
* Crear proyecto en AAP para leer del repositorio del grupo de Gitea - **__15 puntos__**
* Crear job template en AAP - **__10 puntos__**
* Realizar el reto utilizando la colección ``bde.hackathon`` que se encuentra en el Automation Hub - **__50 puntos__**
* Realizar el reto sin utilizar la colección ``bde.hackathon``:
** Realizar el playbook para una unica moneda - **__10 puntos__**
** Realizar el playbook para todas las monedas (bucle) recuperadas de BdE - **__30 puntos__**
** Recuperar la información de BdE - **__15 puntos__**
*** Mostrar la información recuperada de BdE (debug) - **__5 puntos__**
** Recuperar la información del BCE - **__15 puntos__**
*** Mostrar la información recuperada del BCE (debug) - **__5 puntos__**
** Utilizar el módulo ``ansible.builtin.uri`` - **__10 puntos__**
** Actualizar el valor de BdE con la lógica explicada en la descripción del reto - **__25 puntos__**
** Controlar errores (mostrando un mensaje y cancelando el playbook) - **__10 puntos__**