apiVersion: batch/v1
kind: Job
metadata:
  generateName: gitea-setup-
  name: configure-gitea
  namespace: gitea
  annotations:
    argocd.argoproj.io/sync-wave: "29"
  labels:
      app.kubernetes.io/part-of: gitea
      name: configure-gitea
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: git
        image: quay.io/calopezb/git-utils:1.0.0
        # TODO: Read CONFIGURATION using a configmap + ansible
        env:
        - name: GITEA_HOSTNAME
          value: "gitea.gitea.svc.cluster.local:3000"
        command:
        - /bin/sh
        - '-c'
        args:
        - |-
          pwd
          mkdir repository
          cd repository

          echo "-- Creating gitea user"
          curl -X POST \
            -d '{"username":"gitea","password":"openshift","retype":"openshift","email":"gitea@gitea.com","send_notify":false}' \
            -H "Content-Type: application/json" \
            http://$GITEA_HOSTNAME/user/sign_up

          i=0; while [[ $i -lt 10 ]]; do 

          echo "-- Creating developer group-$i --"

          RESPONSE=$(curl -o /dev/null -s -w "%{http_code}\n" -X POST \
            -u gitea:openshift \
            -d '{"email":"group-$i@example.com","full_name": "group-$i","login_name": "develop","must_change_password": false,"password": "ansible","restricted": true,"send_notify": false,"username": "group-$i"}' \
            -H "Content-Type: application/json" \
            http://$GITEA_HOSTNAME/api/v1/admin/users)

          if [ "$RESPONSE" != "201" ]; then
              echo "Error creating developer group-$i, error code: $RESPONSE"
              exit 1
          fi

          echo "-- Creating group-$i-hackathon repository --"
          RESPONSE=$(curl -o /dev/null -s -w "%{http_code}\n" -X POST \
            -u group-$i:ansible \
            -d '{"auto_init": true,"default_branch": "master","gitignores": "VisualStudioCode","name": "group-$i-hackathon","private": true,"trust_model": "default"}' \
            -H "Content-Type: application/json" \
            http://$GITEA_HOSTNAME/api/v1/user/repos)

          if [ "$RESPONSE" != "201" ]; then
              echo "Error creating repository group-$i-hackathon, error code: $RESPONSE"
              exit 1
          fi

          i=$((i+1)); done
          
        imagePullPolicy: Always
      restartPolicy: Never