apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: exchange-rates-apps
spec:
  generators:
  - list:
      elements:
        - name: group-1
        - name: group-2
        - name: group-3
        - name: group-4
        - name: group-5
        - name: group-6
        - name: group-7
        - name: group-8
        - name: group-9
        - name: group-10
  template:
    metadata:
      name: "{{name}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/clbartolome/ansible-hackathon.git
        targetRevision: master
        path: "deploy/exchange-rates-helm"
        helm:
          user: "{{name}}"
          namespace: "{{name}}"
      destination:
        # Default base cluster
        name: in-cluster
        namespace: "{{name}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true