
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
  labels:
    app: exchange
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: backend
spec:
  ports:
    - name: 5000-tcp
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    deployment: backend
  type: ClusterIP
