apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: exchange
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: frontend
spec:
  ports:
    - name: 5000-tcp
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    deployment: frontend
  type: ClusterIP
