    - include_tasks: prepare.yaml

    - name: Create Organizations
      awx.awx.organization:
        controller_host: "{{ aap_host }}"
        controller_username: "admin"
        controller_password: "{{ aap_pass }}"
        validate_certs: false
        name: "group-{{ item }}"
        description: "group-{{ item }} organization" 
        state: present
      loop: "{{ range(10) | list }}"

    - name: Create Users
      awx.awx.user:
        controller_host: "{{ aap_host }}"
        controller_username: "admin"
        controller_password: "{{ aap_pass }}"
        validate_certs: false
        username: "group-{{ item }}"
        password: "ansible"
        state: present
        organization: "group-{{ item }}"
      loop: "{{ range(10) | list }}"

    - name: Configure RBAC
      awx.awx.role:
        controller_host: "{{ aap_host }}"
        controller_username: "admin"
        controller_password: "{{ aap_pass }}"
        validate_certs: false
        user: "group-{{ item }}"
        role: admin
        organization: "group-{{ item }}"
        state: present
      loop: "{{ range(10) | list }}"

    - name: Create SCM credential
      awx.awx.credential:
        controller_host: "{{ aap_host }}"
        controller_username: "admin"
        controller_password: "{{ aap_pass }}"
        validate_certs: false
        name: "group-{{ item }} SCM Credential"
        organization: "group-{{ item }}"
        state: present
        credential_type: Source Control
        inputs:
          username: "group-{{ item }}"
          password: "ansible"
      loop: "{{ range(10) | list }}"

    - name: Add Windows credential
      awx.awx.credential:
        controller_host: "{{ aap_host }}"
        controller_username: "admin"
        controller_password: "{{ aap_pass }}"
        validate_certs: false
        name: "group-{{ item }}"
        description: "group-{{ item }}"
        organization: "group-{{ item }}"
        credential_type: Machine
        inputs:
          username: "group-{{ item }}"
          password: "ansible{{ item }}!!"
        state: present
      loop: "{{ range(10) | list }}"

    - name: Create Projects
      awx.awx.project:
        controller_host: "{{ aap_host }}"
        controller_username: "admin"
        controller_password: "{{ aap_pass }}"
        validate_certs: false
        name: "group-{{ item }}"
        description: "group-{{ item }} project"
        organization: "group-{{ item }}"
        credential: "group-{{ item }} SCM Credential" 
        state: present
        scm_type: git
        scm_url: "https://gitea-gitea.apps.cluster-6gqg4-1.dynamic.redhatworkshops.io/group-{{ item }}/group-{{ item }}-hackathon.git"
      loop: "{{ range(10) | list }}"

    - name: Add Windows inventory
      awx.awx.inventory:
        controller_host: "{{ aap_host }}"
        controller_username: "admin"
        controller_password: "{{ aap_pass }}"
        validate_certs: false
        name: "Windows Inventory for group-{{ item }}"
        description: "Windows Inventory"
        organization: "group-{{ item }}"
        state: present
        variables:
          ansible_user: "group{{ item }}" # change !
          ansible_password: "ansible" #change !
          ansible_port: 5985
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
      loop: "{{ range(10) | list }}"

    - name: Add inventory for localhost"
      awx.awx.inventory:
        controller_host: "{{ aap_host }}"
        controller_username: "admin"
        controller_password: "{{ aap_pass }}"
        validate_certs: false
        name: "Localhost Inventory for group-{{ item }}"
        description: "Localhost Inventory"
        organization: "group-{{ item }}"
        state: present
      loop: "{{ range(10) | list }}"

    - name: Add host Windows Inventory
      awx.awx.host:
        controller_host: "{{ aap_host }}"
        controller_username: "admin"
        controller_password: "{{ aap_pass }}"
        validate_certs: false
        name: "{{ instance.instances[0].public_dns_name }}"
        description: "Windows Host"
        inventory: "Windows Inventory for group-{{ item }}"
        state: present
      loop: "{{ range(10) | list }}"

    - name: Add host for localhost
      awx.awx.host:
        controller_host: "{{ aap_host }}"
        controller_username: "admin"
        controller_password: "{{ aap_pass }}"
        validate_certs: false
        name: localhost
        description: "localhost"
        inventory: "Localhost Inventory for group-{{ item }}"
        variables:
          ansible_connection: local
        state: present
      loop: "{{ range(10) | list }}"
