---
- name: Deploy Ansible Hackathon Environment
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vars.yaml
  environment:
    AWS_ACCESS_KEY_ID: "{{ access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ secret_key }}"
    AWS_REGION: "{{ region }}"

  tasks:

    - name: Deploy Openshift Infra
      ansible.builtin.include_role:
        name: deploy_ocp_infra
    
    - name: Deploy AWS Infra
      ansible.builtin.include_role: 
        name: deploy_aws_infra

    - name: Configure Ansible Controller
      ansible.builtin.include_role:
        name: controller_casc

    - name: Add Windows host to in-memory inventory 
      ansible.builtin.add_host: 
        name: "{{ instance.instances[0].public_dns_name }}"
        groups: windows
        ansible_user: "Administrator"
        ansible_password: "{{ admin_password }}"
        ansible_port: 5985
        ansible_connection: winrm
        ansible_winrm_transport: ntlm

- name: Configure Windows Host
  ansible.builtin.import_playbook: windows.yaml

