- name: Exchange rate challenge
  gather_facts: false
  hosts: localhost
  collections:
    - community.general # due to json_query filter (it has jmespath dependency)
  vars:
    currency: "USD"
    bce_endpoint: "http://localhost:3000/bce_rates/{{ currency }}"
    bde_endpoint: "http://localhost:3000/app_rates"
    get_limit_json_filter: "[?currency=='{{ currency }}'].limit"
    get_value_json_filter: "[?currency=='{{ currency }}'].value"
  tasks:
    - name: Block localhost
      delegate_to: localhost
      block:
        - name: "Get BCE rate for {{ currency }}"
          ansible.builtin.uri:
            url: "{{ bce_endpoint }}"
            return_content: true
          register: bce_reply

        - name: Debug bce_reply
          ansible.builtin.debug:
            msg: "{{ bce_reply.json }}"
            verbosity: 3

        - name: Get BCE value
          ansible.builtin.set_fact:
            bce_value: "{{ bce_reply.json.value }}"

        - name: Get BDE info
          ansible.builtin.uri:
            url: "{{ bde_endpoint }}"
            return_content: true
          register: bde_reply

        - name: Debug bde_reply
          ansible.builtin.debug:
            msg: "{{ bde_reply.json }}"
            verbosity: 3

        - name: Get BDE limit
          ansible.builtin.set_fact:
            bde_limit: "{{ bde_reply.json | community.general.json_query(get_limit_json_filter) | first | float }}"

        - name: Get BDE current value
          ansible.builtin.set_fact:
            bde_value: "{{ bde_reply.json | community.general.json_query(get_value_json_filter) | first | float }}"

        - name: Debug values
          ansible.builtin.debug:
            msg:
              - "Divisa: {{ currency }}"
              - "El valor actual en la web de BDE es {{ bde_value }}."
              - "El límite establecido es de {{ bde_limit }}."
              - "El BCE reporta un tipo de cambio de {{ bce_value }}."

        - name: Set boolean control var
          ansible.builtin.set_fact:
            exceeded_limit: true
          when: bce_value | float > bde_limit | float

        - name: Set new value rate
          ansible.builtin.set_fact:
            new_rate_value: "{{ get_rate_value }}"
          vars:
            get_rate_value: |-
              {%- if exceeded_limit is defined and exceeded_limit is true -%}{{ bde_limit }}{%- else -%}{{ bce_value }}{%- endif -%}

        - name: Debug new value rate
          ansible.builtin.debug:
            msg: "El nuevo valor calculado y que se actualizará en la web de BDE es: {{ new_rate_value }}"

        - name: Update BDE website
          ansible.builtin.uri:
            url: "{{ bde_endpoint }}"
            method: PUT
            body_format: json
            body: >
              {
                "currency": "{{ currency }}",
                "value": {{ new_rate_value | float }}
              }
          register: update_output
          when: new_rate_value != bde_value
          failed_when: "'successfully' not in update_output.json.message"
